name: Authorization Automatad tests

on: 
  push:
    branches:
      - develop
  schedule:
    - cron: "*/10 * * * *"


jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: setup Python
          uses: actions/setup-python@v5
          with: 
            python-version: "3.11"

        - name: Install Chrome
          run: sudo apt-get install google-chrome-stable

        - name: install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install allure-pytest
              
        - name: Run test_header
          if: always()
          run: pytest authorization/tests/test_header.py::TestHeader::test_header_logo --alluredir=allure-results/header
        
        # - name: Run test_signin
        #   if: always()
        #   run: pytest authorization/tests/test_signin.py::TestSignInEmail::test_enter_registered_email --alluredir=allure-results/signin
  
        # - name: Run test_signin_password
        #   run: pytest authorization/tests/test_signin_password.py --alluredir=allure-results/test_signin_password
  
        # - name: Run test_reset_password
        #   run: pytest authorization/tests/test_reset_password.py --alluredir=allure-results/test_reset_password
  
        # - name: Run test_signup
        #   run: pytest authorization/tests/test_signup.py --alluredir=allure-results/test_signup
  
        # - name: Run test_verification_code
        #   run: pytest authorization/tests/test_verification_code.py --alluredir=allure-results/test_verification_code
  
        # - name: Merge Allure Results
        #   run: |
        #     mkdir -p allure-results
        #     cp -r allure-results/* merged-allure-results/ || true

        - name: Merge Allure Results
          run: |
            mkdir -p merged-allure-results
            find allure-results -type f -name "*.json" -exec cp {} merged-allure-results/ \;



        
        - name: Install Java
          uses: actions/setup-java@v4
          with: 
            distribution: 'zulu'
            java-version: '21'
        
        - name: Get Allure history
          uses: actions/checkout@v4
          if: always()
          continue-on-error: true
          with:
            ref: gh-pages
            fetch-depth: 0
            path: gh-pages
        
        - name: Remove old report directories
          run: |
            cd gh-pages
            ls -d */ | grep -v "allure-history" | sort -r | tail -n +4 | xargs rm -rf
          
        # - name: Push changes to gh-pages
        #   run: |
        #     git config user.name "github-actions[bot]"
        #     git config user.email "github-actions[bot]@users.noreply.github.com"
        #     git add .
        #     git commit -m "Cleanup old reports, keeping only the last 3 and excluding allure-history"
        #     git push origin gh-pages

        - name: Build test report
          uses: simple-elf/allure-report-action@v1.7
          if: always()
          continue-on-error: true
          with:
            allure_results: merged-allure-results
            gh_pages: gh-pages
            allure_history: allure-history


        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v4
          with:
            # personal_token: ${{ secrets.MOTHERHASH_TOKEN }}
            # github_token: ${{ secrets.GITHUB_TOKEN }}
            github_token: ${{ secrets.MOTHERHASH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-history
        


  # generate-report:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   name: allure-reports
  #   steps:
  #       - name: Checkout repository
  #         uses: actions/checkout@v4

        
